### ISSUE TITLE
Is normal this spam??

### ISSUE THREAD

**Issue by iiSammy** [Zaggy1024/LC_PathfindingLagFix#1]
Start in the lane 1516 when the centepide spawn
[LogOutput.log](https://github.com/Zaggy1024/LC_PathfindingLagFix/files/14078529/LogOutput.log)
![Screenshot 2024-01-29 014847](https://github.com/Zaggy1024/LC_PathfindingLagFix/assets/21334991/cc016307-ce7c-42ce-9de2-673097560e7c)

**Comment by Zaggy1024** [comment]
Ah, that's just some debug logging that I had forgotten to remove. I actually thought I had released a version with this removed, but I guess not, so let me do that now.

**Comment by iiSammy** [comment]
Thanks for answering :)

**Comment by Zaggy1024** [comment]
Pushed version 1.2.1 to remove the debug spam.
