### ISSUE TITLE
[Issue? Question] is this mod cause those error log?

### ISSUE THREAD

**Issue by CoolLKKPS** [Zaggy1024/LC_PathfindingLagFix#3]
![IMG_20240505_045907](https://github.com/Zaggy1024/LC_PathfindingLagFix/assets/96377775/cc214c0b-32b8-43fc-a0ae-2884148e5dd3)
@Zaggy1024

**Comment by Zaggy1024** [comment]
That's a vanilla issue, unfortunately Unity likes to spam these errors whenever the game tries to path an enemy that's fallen out of the playable area.

With PathfindingLagFix, that shouldn't affect things too much, but it's a somewhat difficult issue to fix at the source.

**Comment by CoolLKKPS** [comment]
tbh, if i got this log, i believe at least one creature will stuck in somewhere, but yea if this is vanilla issue, i hope this issue get fix asap
