### ISSUE TITLE
[v55] issue when do AI MoveNext, will throw exception

### ISSUE THREAD

**Issue by CoolLKKPS** [Zaggy1024/LC_PathfindingLagFix#5]
same as topic

**Comment by Zaggy1024** [comment]
Any stack trace? This doesn't really tell me much.

**Comment by CoolLKKPS** [comment]
tbh really tired for me at this moment, if u need error log i will provide in tomorrow, but just always see the bracken and u will see the error log

**Comment by Zaggy1024** [comment]
Did the bracken also behave differently, like getting stuck? I played v55 earlier and I didn't notice anything, but I wasn't watching the log.

**Comment by CoolLKKPS** [comment]
@Zaggy1024 
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) PathfindingLagFix.Patches.PatchFlowermanAI.DMD<PathfindingLagFix.Patches.PatchFlowermanAI::FinishChoosingPlayerEvasionLocation>(FlowermanAI,UnityEngine.Transform)
PathfindingLagFix.Patches.PatchFlowermanAI+<ChoosePlayerEvasionLocation>d__8.MoveNext () (at <240b7872d59045de9453120dab2c3e1e>:IL_00C5)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by Zaggy1024** [comment]
That's the full stack trace? It seems like whatever error is happening would probably happen without PathfindingLagFix, since the code where that occurs is largely copied from the vanilla code. I haven't been able to get this to happen on my end yet, so it might be another mod messing with the bracken that's causing this.

If you could provide a profile code and some confirmed steps to reproduce the issue consistently, then maybe I can determine if that's the case.

**Comment by CoolLKKPS** [comment]
uh maybe "devmode" mod idk? but i reproduce that issue by just run close to the bracken kill range while bracken are retreating, in dev test room, but hmm, i remember i did disable the mod call "snatchinbracken", so if u cannot reproduce maybe u need to try that mod

**Comment by CoolLKKPS** [comment]
and my modpack are always available here: https://1drv.ms/f/s!AlwrljXcImfClQt9MgB2BOZ-XA9h

**Comment by Zaggy1024** [comment]
Looks like this was (kind of) caused by SnatchinBracken as you mentioned. The error should be harmless, but I'll be able to patch this pretty easily.

**Comment by JohnMetroid** [comment]
I have seen this error a number of times, and naively assumed it was a vanilla bug.  I don't use SnatchinBracken, so just figured I'd echo what I've seen here.

Cheers

```
[01:49:13.2387008] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) PathfindingLagFix.Patches.PatchFlowermanAI.DMD<PathfindingLagFix.Patches.PatchFlowermanAI::FinishChoosingPlayerEvasionLocation>(FlowermanAI,UnityEngine.Transform)
PathfindingLagFix.Patches.PatchFlowermanAI+<ChoosePlayerEvasionLocation>d__8.MoveNext () (at <240b7872d59045de9453120dab2c3e1e>:IL_00C5)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

[01:49:13.2387008] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) PathfindingLagFix.Patches.PatchFlowermanAI.DMD<PathfindingLagFix.Patches.PatchFlowermanAI::FinishChoosingPlayerEvasionLocation>(FlowermanAI,UnityEngine.Transform)
PathfindingLagFix.Patches.PatchFlowermanAI+<ChoosePlayerEvasionLocation>d__8.MoveNext () (at <240b7872d59045de9453120dab2c3e1e>:IL_00C5)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)
```
